spring.application.name=PetClinic

spring.datasource.url=jdbc:postgresql://localhost:5432/iis
spring.datasource.username=postgres
spring.datasource.password=ftn
spring.datasource.driver-class-name=org.postgresql.Driver

spring.jpa.hibernate.ddl-auto=create-drop
spring.jpa.show-sql=true
spring.jpa.properties.hibernate.dialect=org.hibernate.dialect.PostgreSQLDialect
#
#server.port=8081
#spring.application.name=PetClinic
#
#spring.datasource.url=jdbc:oracle:thin:@localhost:1521:xe
#spring.datasource.username=system
#spring.datasource.password=ftn
#spring.datasource.driver-class-name=oracle.jdbc.OracleDriver
#
#spring.datasource.hikari.connection-properties=user.language=en,user.region=US
#
## OVO JE BITNO: 'create' ?e obrisati sve i napraviti ih REDOM ponovo
#spring.jpa.hibernate.ddl-auto=create
#spring.jpa.show-sql=true
#
#spring.jpa.database-platform=org.hibernate.dialect.OracleDialect
#spring.jpa.properties.hibernate.dialect=org.hibernate.dialect.OracleDialect